services:
  web:
    build: .
    container_name: nc_api_service
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - --error-logfile - --log-level info run:app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://xx:xx@xx:xx/xx
      - JWT_SECRET_KEY=your_secret_key
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_service
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: nginx-pm