"""Add used_in_collaborative in users table

Revision ID: 1ff3f892087b
Revises: f5131a61ebde
Create Date: 2025-06-08 15:48:04.757244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff3f892087b'
down_revision = 'f5131a61ebde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_in_collaborative', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('used_in_collaborative')

    # ### end Alembic commands ###
