"""add total_interactions, total_users and image_banner_url

Revision ID: 58da06d51dcd
Revises: cbc54ff62616
Create Date: 2025-06-03 13:14:36.569931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da06d51dcd'
down_revision = 'cbc54ff62616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_interactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_users', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_banner_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('image_banner_url')
        batch_op.drop_column('total_users')
        batch_op.drop_column('total_interactions')

    # ### end Alembic commands ###
