"""Add unique constraint to user_interactions

Revision ID: 9222beb513d9
Revises: 15952ec4eaff
Create Date: 2025-06-06 21:27:45.720319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9222beb513d9'
down_revision = '15952ec4eaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_course_interaction', ['user_id', 'course_id', 'interaction_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_course_interaction', type_='unique')

    # ### end Alembic commands ###
