"""Initial migration

Revision ID: 9bd74339b0fd
Revises: 
Create Date: 2025-05-17 16:12:09.323602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd74339b0fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('num_subscribers', sa.Integer(), nullable=True),
    sa.Column('num_reviews', sa.Integer(), nullable=True),
    sa.Column('num_lectures', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('content_duration', sa.Float(), nullable=False),
    sa.Column('published_timestamp', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
