"""Use course_id as index

Revision ID: ab3a330bc56c
Revises: d75d4c303974
Create Date: 2025-05-17 16:27:10.617380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3a330bc56c'
down_revision = 'd75d4c303974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('course_id')
        batch_op.create_index(batch_op.f('ix_courses_course_id'), ['course_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_course_id'))
        batch_op.create_index('course_id', ['course_id'], unique=True)

    # ### end Alembic commands ###
