"""Fix foreign key reference

Revision ID: f5131a61ebde
Revises: 9222beb513d9
Create Date: 2025-06-06 21:44:08.631676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5131a61ebde'
down_revision = '9222beb513d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_interactions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_interactions_ibfk_1'), 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###
